//
//  HTMLReportGenerator.swift
//  mergen
//
//  Created by Samet Sazak on 7.04.2023.
//

import Foundation
import SwiftUI
import UniformTypeIdentifiers

struct HTMLReportGenerator {
    
    let scanResults: [Vulnerability]
    
    init(scanResults: [Vulnerability]) {
        self.scanResults = scanResults
    }
    
    func generateHTMLReport() -> String {
        var html = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>Mergen - Scan Results</title>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
            </head>

        <style>

            body {
                background-image: linear-gradient(to right top, #678fc4, #648bbf, #6186bb, #5f82b6, #5c7eb2, #587aae, #5575aa, #5171a6, #4a6ba1, #44669c, #3d6098, #365b93);
                font-family: Arial, sans-serif;
                color:white;
            }
            h1 {
                text-align: center;
                margin-bottom: 30px;
                color:white;
            }
            .container {
                max-width: 80%;
                margin: auto;
                color: #ffffff;
            }
            table {
                background-image: linear-gradient(to right top, #678fc4, #648bbf, #6186bb, #5f82b6, #5c7eb2, #587aae, #5575aa, #5171a6, #4a6ba1, #44669c, #3d6098, #365b93);
                border-collapse: collapse;
                width: 100%;
                color: #ffffff;
            }
            th, td {
                border: 1px solid #dee2e6;
                padding: 8px;
                text-align: left;
                color: #ffffff;
            }
            th {
                font-weight: 600;
                color: #ffffff;
            }
        </style>

        <body>
        <h1 style="text-align: center;">Mergen - Security Audit Report</h1>
        <h6 style="text-align: center;">CIS Apple macOS 26 Tahoe Benchmark v1.0.0 — Generated by Mergen</h6>
        <br>
            <div class="container">
                <table class="table table-striped table-dark">
                    <thead>
                        <tr>
                            <th>CIS ID</th>
                            <th>Name</th>
                            <th>Category</th>
                            <th>Severity</th>
                            <th>Result</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
        """

        for vulnerability in scanResults {
            let severityIcon: String
            switch vulnerability.severity {
            case "Low":
                severityIcon = "fas fa-arrow-down text-success"
            case "Medium":
                severityIcon = "fas fa-arrow-right text-warning"
            case "High":
                severityIcon = "fas fa-arrow-up text-danger"
            default:
                severityIcon = "fas fa-question text-secondary"
            }

            let checkStatusIcon: String
            let checkStatusColor: String
            switch vulnerability.checkstatus {
            case "Green":
                checkStatusIcon = "fas fa-check-circle"
                checkStatusColor = "text-success"
            case "Yellow":
                checkStatusIcon = "fas fa-exclamation-circle"
                checkStatusColor = "text-warning"
            case "Red":
                checkStatusIcon = "fas fa-times-circle"
                checkStatusColor = "text-danger"
            case "Blue":
                checkStatusIcon = "fas fa-info-circle"
                checkStatusColor = "text-info"
            default:
                checkStatusIcon = "fas fa-question-circle"
                checkStatusColor = "text-secondary"
            }

            html += """
                <tr>
                    <td>\(vulnerability.cisID.isEmpty ? "—" : vulnerability.cisID)</td>
                    <td>\(vulnerability.name)</td>
                    <td>\(vulnerability.category)</td>
                    <td><i class="\(severityIcon)"></i> \(vulnerability.severity)</td>
                    <td>\(vulnerability.status ?? "N/A")</td>
                    <td><i class="\(checkStatusIcon) \(checkStatusColor)"></i></td>
            </tr>
        """
    }

    html += """
                </tbody>
            </table>
        </div>
    </body>
    </html>
    """

        return html
    
    }
}

struct FileUtils {
    static func saveHTMLStringToFile(_ htmlString: String) {
        let savePanel = NSSavePanel()
        savePanel.nameFieldStringValue = "MergenResult.html"
        savePanel.allowedContentTypes = [UTType.html]

        if savePanel.runModal() == .OK, let url = savePanel.url {
            do {
                try htmlString.write(to: url, atomically: true, encoding: .utf8)
                print("HTML file saved to \(url)")
            } catch {
                print("Error saving HTML file: \(error)")
            }
        }
    }
}
